// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/spot-lever-token/info
func (c *Client) GetSpotLeverTokenInfo(req models.GetSpotLeverTokenInfoRequest) (*models.GetSpotLeverTokenInfoResponse, error) {
	var respBody models.Response[models.GetSpotLeverTokenInfoResponse]
	if err := c.GET("/v5/spot-lever-token/info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spot-lever-token/order-record
func (c *Client) GetSpotLeverTokenOrderRecord(req models.GetSpotLeverTokenOrderRecordRequest) (*models.GetSpotLeverTokenOrderRecordResponse, error) {
	var respBody models.Response[models.GetSpotLeverTokenOrderRecordResponse]
	if err := c.GET("/v5/spot-lever-token/order-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spot-lever-token/reference
func (c *Client) GetSpotLeverTokenReference(req models.GetSpotLeverTokenReferenceRequest) (*models.GetSpotLeverTokenReferenceResponse, error) {
	var respBody models.Response[models.GetSpotLeverTokenReferenceResponse]
	if err := c.GET("/v5/spot-lever-token/reference", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spot-lever-token/purchase
func (c *Client) PostSpotLeverTokenPurchase(req models.PostSpotLeverTokenPurchaseRequest) (*models.PostSpotLeverTokenPurchaseResponse, error) {
	var respBody models.Response[models.PostSpotLeverTokenPurchaseResponse]
	if err := c.POST("/v5/spot-lever-token/purchase", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spot-lever-token/redeem
func (c *Client) PostSpotLeverTokenRedeem(req models.PostSpotLeverTokenRedeemRequest) (*models.PostSpotLeverTokenRedeemResponse, error) {
	var respBody models.Response[models.PostSpotLeverTokenRedeemResponse]
	if err := c.POST("/v5/spot-lever-token/redeem", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

