// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/crypto-loan-common/adjustment-history
func (c *Client) GetCryptoLoanCommonAdjustmentHistory(req models.GetCryptoLoanCommonAdjustmentHistoryRequest) (*models.GetCryptoLoanCommonAdjustmentHistoryResponse, error) {
	var respBody models.Response[models.GetCryptoLoanCommonAdjustmentHistoryResponse]
	if err := c.GET("/v5/crypto-loan-common/adjustment-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-common/collateral-data
func (c *Client) GetCryptoLoanCommonCollateralData(req models.GetCryptoLoanCommonCollateralDataRequest) (*models.GetCryptoLoanCommonCollateralDataResponse, error) {
	var respBody models.Response[models.GetCryptoLoanCommonCollateralDataResponse]
	if err := c.GET("/v5/crypto-loan-common/collateral-data", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-common/loanable-data
func (c *Client) GetCryptoLoanCommonLoanableData(req models.GetCryptoLoanCommonLoanableDataRequest) (*models.GetCryptoLoanCommonLoanableDataResponse, error) {
	var respBody models.Response[models.GetCryptoLoanCommonLoanableDataResponse]
	if err := c.GET("/v5/crypto-loan-common/loanable-data", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-common/max-collateral-amount
func (c *Client) GetCryptoLoanCommonMaxCollateralAmount(req models.GetCryptoLoanCommonMaxCollateralAmountRequest) (*models.GetCryptoLoanCommonMaxCollateralAmountResponse, error) {
	var respBody models.Response[models.GetCryptoLoanCommonMaxCollateralAmountResponse]
	if err := c.GET("/v5/crypto-loan-common/max-collateral-amount", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-common/position
func (c *Client) GetCryptoLoanCommonPosition(req models.GetCryptoLoanCommonPositionRequest) (*models.GetCryptoLoanCommonPositionResponse, error) {
	var respBody models.Response[models.GetCryptoLoanCommonPositionResponse]
	if err := c.GET("/v5/crypto-loan-common/position", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/borrow-contract-info
func (c *Client) GetCryptoLoanFixedBorrowContractInfo(req models.GetCryptoLoanFixedBorrowContractInfoRequest) (*models.GetCryptoLoanFixedBorrowContractInfoResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedBorrowContractInfoResponse]
	if err := c.GET("/v5/crypto-loan-fixed/borrow-contract-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/borrow-order-info
func (c *Client) GetCryptoLoanFixedBorrowOrderInfo(req models.GetCryptoLoanFixedBorrowOrderInfoRequest) (*models.GetCryptoLoanFixedBorrowOrderInfoResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedBorrowOrderInfoResponse]
	if err := c.GET("/v5/crypto-loan-fixed/borrow-order-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/borrow-order-quote
func (c *Client) GetCryptoLoanFixedBorrowOrderQuote(req models.GetCryptoLoanFixedBorrowOrderQuoteRequest) (*models.GetCryptoLoanFixedBorrowOrderQuoteResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedBorrowOrderQuoteResponse]
	if err := c.GET("/v5/crypto-loan-fixed/borrow-order-quote", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/repayment-history
func (c *Client) GetCryptoLoanFixedRepaymentHistory(req models.GetCryptoLoanFixedRepaymentHistoryRequest) (*models.GetCryptoLoanFixedRepaymentHistoryResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedRepaymentHistoryResponse]
	if err := c.GET("/v5/crypto-loan-fixed/repayment-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/supply-contract-info
func (c *Client) GetCryptoLoanFixedSupplyContractInfo(req models.GetCryptoLoanFixedSupplyContractInfoRequest) (*models.GetCryptoLoanFixedSupplyContractInfoResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedSupplyContractInfoResponse]
	if err := c.GET("/v5/crypto-loan-fixed/supply-contract-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/supply-order-info
func (c *Client) GetCryptoLoanFixedSupplyOrderInfo(req models.GetCryptoLoanFixedSupplyOrderInfoRequest) (*models.GetCryptoLoanFixedSupplyOrderInfoResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedSupplyOrderInfoResponse]
	if err := c.GET("/v5/crypto-loan-fixed/supply-order-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-fixed/supply-order-quote
func (c *Client) GetCryptoLoanFixedSupplyOrderQuote(req models.GetCryptoLoanFixedSupplyOrderQuoteRequest) (*models.GetCryptoLoanFixedSupplyOrderQuoteResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFixedSupplyOrderQuoteResponse]
	if err := c.GET("/v5/crypto-loan-fixed/supply-order-quote", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-flexible/borrow-history
func (c *Client) GetCryptoLoanFlexibleBorrowHistory(req models.GetCryptoLoanFlexibleBorrowHistoryRequest) (*models.GetCryptoLoanFlexibleBorrowHistoryResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFlexibleBorrowHistoryResponse]
	if err := c.GET("/v5/crypto-loan-flexible/borrow-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-flexible/ongoing-coin
func (c *Client) GetCryptoLoanFlexibleOngoingCoin(req models.GetCryptoLoanFlexibleOngoingCoinRequest) (*models.GetCryptoLoanFlexibleOngoingCoinResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFlexibleOngoingCoinResponse]
	if err := c.GET("/v5/crypto-loan-flexible/ongoing-coin", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/crypto-loan-flexible/repayment-history
func (c *Client) GetCryptoLoanFlexibleRepaymentHistory(req models.GetCryptoLoanFlexibleRepaymentHistoryRequest) (*models.GetCryptoLoanFlexibleRepaymentHistoryResponse, error) {
	var respBody models.Response[models.GetCryptoLoanFlexibleRepaymentHistoryResponse]
	if err := c.GET("/v5/crypto-loan-flexible/repayment-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-common/adjust-ltv
func (c *Client) PostCryptoLoanCommonAdjustLtv(req models.PostCryptoLoanCommonAdjustLtvRequest) (*models.PostCryptoLoanCommonAdjustLtvResponse, error) {
	var respBody models.Response[models.PostCryptoLoanCommonAdjustLtvResponse]
	if err := c.POST("/v5/crypto-loan-common/adjust-ltv", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-fixed/borrow
func (c *Client) PostCryptoLoanFixedBorrow(req models.PostCryptoLoanFixedBorrowRequest) (*models.PostCryptoLoanFixedBorrowResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFixedBorrowResponse]
	if err := c.POST("/v5/crypto-loan-fixed/borrow", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-fixed/borrow-order-cancel
func (c *Client) PostCryptoLoanFixedBorrowOrderCancel(req models.PostCryptoLoanFixedBorrowOrderCancelRequest) (*models.PostCryptoLoanFixedBorrowOrderCancelResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFixedBorrowOrderCancelResponse]
	if err := c.POST("/v5/crypto-loan-fixed/borrow-order-cancel", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-fixed/fully-repay
func (c *Client) PostCryptoLoanFixedFullyRepay(req models.PostCryptoLoanFixedFullyRepayRequest) (*models.PostCryptoLoanFixedFullyRepayResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFixedFullyRepayResponse]
	if err := c.POST("/v5/crypto-loan-fixed/fully-repay", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-fixed/supply
func (c *Client) PostCryptoLoanFixedSupply(req models.PostCryptoLoanFixedSupplyRequest) (*models.PostCryptoLoanFixedSupplyResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFixedSupplyResponse]
	if err := c.POST("/v5/crypto-loan-fixed/supply", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-fixed/supply-order-cancel
func (c *Client) PostCryptoLoanFixedSupplyOrderCancel(req models.PostCryptoLoanFixedSupplyOrderCancelRequest) (*models.PostCryptoLoanFixedSupplyOrderCancelResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFixedSupplyOrderCancelResponse]
	if err := c.POST("/v5/crypto-loan-fixed/supply-order-cancel", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-flexible/borrow
func (c *Client) PostCryptoLoanFlexibleBorrow(req models.PostCryptoLoanFlexibleBorrowRequest) (*models.PostCryptoLoanFlexibleBorrowResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFlexibleBorrowResponse]
	if err := c.POST("/v5/crypto-loan-flexible/borrow", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/crypto-loan-flexible/repay
func (c *Client) PostCryptoLoanFlexibleRepay(req models.PostCryptoLoanFlexibleRepayRequest) (*models.PostCryptoLoanFlexibleRepayResponse, error) {
	var respBody models.Response[models.PostCryptoLoanFlexibleRepayResponse]
	if err := c.POST("/v5/crypto-loan-flexible/repay", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

