// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/spot-margin-trade/collateral
func (c *Client) GetSpotMarginTradeCollateral(req models.GetSpotMarginTradeCollateralRequest) (*models.GetSpotMarginTradeCollateralResponse, error) {
	var respBody models.Response[models.GetSpotMarginTradeCollateralResponse]
	if err := c.GET("/v5/spot-margin-trade/collateral", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spot-margin-trade/data
func (c *Client) GetSpotMarginTradeData(req models.GetSpotMarginTradeDataRequest) (*models.GetSpotMarginTradeDataResponse, error) {
	var respBody models.Response[models.GetSpotMarginTradeDataResponse]
	if err := c.GET("/v5/spot-margin-trade/data", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spot-margin-trade/interest-rate-history
func (c *Client) GetSpotMarginTradeInterestRateHistory(req models.GetSpotMarginTradeInterestRateHistoryRequest) (*models.GetSpotMarginTradeInterestRateHistoryResponse, error) {
	var respBody models.Response[models.GetSpotMarginTradeInterestRateHistoryResponse]
	if err := c.GET("/v5/spot-margin-trade/interest-rate-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spot-margin-trade/state
func (c *Client) GetSpotMarginTradeState(req models.GetSpotMarginTradeStateRequest) (*models.GetSpotMarginTradeStateResponse, error) {
	var respBody models.Response[models.GetSpotMarginTradeStateResponse]
	if err := c.GET("/v5/spot-margin-trade/state", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spot-margin-trade/set-leverage
func (c *Client) PostSpotMarginTradeSetLeverage(req models.PostSpotMarginTradeSetLeverageRequest) (*models.PostSpotMarginTradeSetLeverageResponse, error) {
	var respBody models.Response[models.PostSpotMarginTradeSetLeverageResponse]
	if err := c.POST("/v5/spot-margin-trade/set-leverage", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spot-margin-trade/switch-mode
func (c *Client) PostSpotMarginTradeSwitchMode(req models.PostSpotMarginTradeSwitchModeRequest) (*models.PostSpotMarginTradeSwitchModeResponse, error) {
	var respBody models.Response[models.PostSpotMarginTradeSwitchModeResponse]
	if err := c.POST("/v5/spot-margin-trade/switch-mode", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

