// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/pre-upgrade/account/transaction-log
func (c *Client) GetPreUpgradeAccountTransactionLog(req models.GetPreUpgradeAccountTransactionLogRequest) (*models.GetPreUpgradeAccountTransactionLogResponse, error) {
	var respBody models.Response[models.GetPreUpgradeAccountTransactionLogResponse]
	if err := c.GET("/v5/pre-upgrade/account/transaction-log", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/pre-upgrade/asset/delivery-record
func (c *Client) GetPreUpgradeAssetDeliveryRecord(req models.GetPreUpgradeAssetDeliveryRecordRequest) (*models.GetPreUpgradeAssetDeliveryRecordResponse, error) {
	var respBody models.Response[models.GetPreUpgradeAssetDeliveryRecordResponse]
	if err := c.GET("/v5/pre-upgrade/asset/delivery-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/pre-upgrade/asset/settlement-record
func (c *Client) GetPreUpgradeAssetSettlementRecord(req models.GetPreUpgradeAssetSettlementRecordRequest) (*models.GetPreUpgradeAssetSettlementRecordResponse, error) {
	var respBody models.Response[models.GetPreUpgradeAssetSettlementRecordResponse]
	if err := c.GET("/v5/pre-upgrade/asset/settlement-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/pre-upgrade/execution/list
func (c *Client) GetPreUpgradeExecutionList(req models.GetPreUpgradeExecutionListRequest) (*models.GetPreUpgradeExecutionListResponse, error) {
	var respBody models.Response[models.GetPreUpgradeExecutionListResponse]
	if err := c.GET("/v5/pre-upgrade/execution/list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/pre-upgrade/order/history
func (c *Client) GetPreUpgradeOrderHistory(req models.GetPreUpgradeOrderHistoryRequest) (*models.GetPreUpgradeOrderHistoryResponse, error) {
	var respBody models.Response[models.GetPreUpgradeOrderHistoryResponse]
	if err := c.GET("/v5/pre-upgrade/order/history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/pre-upgrade/position/closed-pnl
func (c *Client) GetPreUpgradePositionClosedPnl(req models.GetPreUpgradePositionClosedPnlRequest) (*models.GetPreUpgradePositionClosedPnlResponse, error) {
	var respBody models.Response[models.GetPreUpgradePositionClosedPnlResponse]
	if err := c.GET("/v5/pre-upgrade/position/closed-pnl", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

