// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/asset/coin/query-info
func (c *Client) GetAssetCoinQueryInfo(req models.GetAssetCoinQueryInfoRequest) (*models.GetAssetCoinQueryInfoResponse, error) {
	var respBody models.Response[models.GetAssetCoinQueryInfoResponse]
	if err := c.GET("/v5/asset/coin/query-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/delivery-record
func (c *Client) GetAssetDeliveryRecord(req models.GetAssetDeliveryRecordRequest) (*models.GetAssetDeliveryRecordResponse, error) {
	var respBody models.Response[models.GetAssetDeliveryRecordResponse]
	if err := c.GET("/v5/asset/delivery-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/deposit/query-address
func (c *Client) GetAssetDepositQueryAddress(req models.GetAssetDepositQueryAddressRequest) (*models.GetAssetDepositQueryAddressResponse, error) {
	var respBody models.Response[models.GetAssetDepositQueryAddressResponse]
	if err := c.GET("/v5/asset/deposit/query-address", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/deposit/query-internal-record
func (c *Client) GetAssetDepositQueryInternalRecord(req models.GetAssetDepositQueryInternalRecordRequest) (*models.GetAssetDepositQueryInternalRecordResponse, error) {
	var respBody models.Response[models.GetAssetDepositQueryInternalRecordResponse]
	if err := c.GET("/v5/asset/deposit/query-internal-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/deposit/query-record
func (c *Client) GetAssetDepositQueryRecord(req models.GetAssetDepositQueryRecordRequest) (*models.GetAssetDepositQueryRecordResponse, error) {
	var respBody models.Response[models.GetAssetDepositQueryRecordResponse]
	if err := c.GET("/v5/asset/deposit/query-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/deposit/query-sub-member-address
func (c *Client) GetAssetDepositQuerySubMemberAddress(req models.GetAssetDepositQuerySubMemberAddressRequest) (*models.GetAssetDepositQuerySubMemberAddressResponse, error) {
	var respBody models.Response[models.GetAssetDepositQuerySubMemberAddressResponse]
	if err := c.GET("/v5/asset/deposit/query-sub-member-address", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/deposit/query-sub-member-record
func (c *Client) GetAssetDepositQuerySubMemberRecord(req models.GetAssetDepositQuerySubMemberRecordRequest) (*models.GetAssetDepositQuerySubMemberRecordResponse, error) {
	var respBody models.Response[models.GetAssetDepositQuerySubMemberRecordResponse]
	if err := c.GET("/v5/asset/deposit/query-sub-member-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/exchange/convert-result-query
func (c *Client) GetAssetExchangeConvertResultQuery(req models.GetAssetExchangeConvertResultQueryRequest) (*models.GetAssetExchangeConvertResultQueryResponse, error) {
	var respBody models.Response[models.GetAssetExchangeConvertResultQueryResponse]
	if err := c.GET("/v5/asset/exchange/convert-result-query", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/exchange/order-record
func (c *Client) GetAssetExchangeOrderRecord(req models.GetAssetExchangeOrderRecordRequest) (*models.GetAssetExchangeOrderRecordResponse, error) {
	var respBody models.Response[models.GetAssetExchangeOrderRecordResponse]
	if err := c.GET("/v5/asset/exchange/order-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/exchange/query-coin-list
func (c *Client) GetAssetExchangeQueryCoinList(req models.GetAssetExchangeQueryCoinListRequest) (*models.GetAssetExchangeQueryCoinListResponse, error) {
	var respBody models.Response[models.GetAssetExchangeQueryCoinListResponse]
	if err := c.GET("/v5/asset/exchange/query-coin-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/exchange/query-convert-history
func (c *Client) GetAssetExchangeQueryConvertHistory(req models.GetAssetExchangeQueryConvertHistoryRequest) (*models.GetAssetExchangeQueryConvertHistoryResponse, error) {
	var respBody models.Response[models.GetAssetExchangeQueryConvertHistoryResponse]
	if err := c.GET("/v5/asset/exchange/query-convert-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/settlement-record
func (c *Client) GetAssetSettlementRecord(req models.GetAssetSettlementRecordRequest) (*models.GetAssetSettlementRecordResponse, error) {
	var respBody models.Response[models.GetAssetSettlementRecordResponse]
	if err := c.GET("/v5/asset/settlement-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-account-coin-balance
func (c *Client) GetAssetTransferQueryAccountCoinBalance(req models.GetAssetTransferQueryAccountCoinBalanceRequest) (*models.GetAssetTransferQueryAccountCoinBalanceResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryAccountCoinBalanceResponse]
	if err := c.GET("/v5/asset/transfer/query-account-coin-balance", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-account-coins-balance
func (c *Client) GetAssetTransferQueryAccountCoinsBalance(req models.GetAssetTransferQueryAccountCoinsBalanceRequest) (*models.GetAssetTransferQueryAccountCoinsBalanceResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryAccountCoinsBalanceResponse]
	if err := c.GET("/v5/asset/transfer/query-account-coins-balance", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-asset-info
func (c *Client) GetAssetTransferQueryAssetInfo(req models.GetAssetTransferQueryAssetInfoRequest) (*models.GetAssetTransferQueryAssetInfoResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryAssetInfoResponse]
	if err := c.GET("/v5/asset/transfer/query-asset-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-inter-transfer-list
func (c *Client) GetAssetTransferQueryInterTransferList(req models.GetAssetTransferQueryInterTransferListRequest) (*models.GetAssetTransferQueryInterTransferListResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryInterTransferListResponse]
	if err := c.GET("/v5/asset/transfer/query-inter-transfer-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-sub-member-list
func (c *Client) GetAssetTransferQuerySubMemberList(req models.GetAssetTransferQuerySubMemberListRequest) (*models.GetAssetTransferQuerySubMemberListResponse, error) {
	var respBody models.Response[models.GetAssetTransferQuerySubMemberListResponse]
	if err := c.GET("/v5/asset/transfer/query-sub-member-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-transfer-coin-list
func (c *Client) GetAssetTransferQueryTransferCoinList(req models.GetAssetTransferQueryTransferCoinListRequest) (*models.GetAssetTransferQueryTransferCoinListResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryTransferCoinListResponse]
	if err := c.GET("/v5/asset/transfer/query-transfer-coin-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/transfer/query-universal-transfer-list
func (c *Client) GetAssetTransferQueryUniversalTransferList(req models.GetAssetTransferQueryUniversalTransferListRequest) (*models.GetAssetTransferQueryUniversalTransferListResponse, error) {
	var respBody models.Response[models.GetAssetTransferQueryUniversalTransferListResponse]
	if err := c.GET("/v5/asset/transfer/query-universal-transfer-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/withdraw/query-record
func (c *Client) GetAssetWithdrawQueryRecord(req models.GetAssetWithdrawQueryRecordRequest) (*models.GetAssetWithdrawQueryRecordResponse, error) {
	var respBody models.Response[models.GetAssetWithdrawQueryRecordResponse]
	if err := c.GET("/v5/asset/withdraw/query-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/withdraw/vasp/list
func (c *Client) GetAssetWithdrawVaspList(req models.GetAssetWithdrawVaspListRequest) (*models.GetAssetWithdrawVaspListResponse, error) {
	var respBody models.Response[models.GetAssetWithdrawVaspListResponse]
	if err := c.GET("/v5/asset/withdraw/vasp/list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/asset/withdraw/withdrawable-amount
func (c *Client) GetAssetWithdrawWithdrawableAmount(req models.GetAssetWithdrawWithdrawableAmountRequest) (*models.GetAssetWithdrawWithdrawableAmountResponse, error) {
	var respBody models.Response[models.GetAssetWithdrawWithdrawableAmountResponse]
	if err := c.GET("/v5/asset/withdraw/withdrawable-amount", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/deposit/deposit-to-account
func (c *Client) PostAssetDepositDepositToAccount(req models.PostAssetDepositDepositToAccountRequest) (*models.PostAssetDepositDepositToAccountResponse, error) {
	var respBody models.Response[models.PostAssetDepositDepositToAccountResponse]
	if err := c.POST("/v5/asset/deposit/deposit-to-account", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/exchange/convert-execute
func (c *Client) PostAssetExchangeConvertExecute(req models.PostAssetExchangeConvertExecuteRequest) (*models.PostAssetExchangeConvertExecuteResponse, error) {
	var respBody models.Response[models.PostAssetExchangeConvertExecuteResponse]
	if err := c.POST("/v5/asset/exchange/convert-execute", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/exchange/quote-apply
func (c *Client) PostAssetExchangeQuoteApply(req models.PostAssetExchangeQuoteApplyRequest) (*models.PostAssetExchangeQuoteApplyResponse, error) {
	var respBody models.Response[models.PostAssetExchangeQuoteApplyResponse]
	if err := c.POST("/v5/asset/exchange/quote-apply", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/transfer/inter-transfer
func (c *Client) PostAssetTransferInterTransfer(req models.PostAssetTransferInterTransferRequest) (*models.PostAssetTransferInterTransferResponse, error) {
	var respBody models.Response[models.PostAssetTransferInterTransferResponse]
	if err := c.POST("/v5/asset/transfer/inter-transfer", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/transfer/universal-transfer
func (c *Client) PostAssetTransferUniversalTransfer(req models.PostAssetTransferUniversalTransferRequest) (*models.PostAssetTransferUniversalTransferResponse, error) {
	var respBody models.Response[models.PostAssetTransferUniversalTransferResponse]
	if err := c.POST("/v5/asset/transfer/universal-transfer", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/withdraw/cancel
func (c *Client) PostAssetWithdrawCancel(req models.PostAssetWithdrawCancelRequest) (*models.PostAssetWithdrawCancelResponse, error) {
	var respBody models.Response[models.PostAssetWithdrawCancelResponse]
	if err := c.POST("/v5/asset/withdraw/cancel", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/asset/withdraw/create
func (c *Client) PostAssetWithdrawCreate(req models.PostAssetWithdrawCreateRequest) (*models.PostAssetWithdrawCreateResponse, error) {
	var respBody models.Response[models.PostAssetWithdrawCreateResponse]
	if err := c.POST("/v5/asset/withdraw/create", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

