// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/asset/deposit/query-allowed-list
func (c *Client) GetAssetDepositQueryAllowedList(req models.GetAssetDepositQueryAllowedListRequest) (*models.GetAssetDepositQueryAllowedListResponse, error) {
	var respBody models.Response[models.GetAssetDepositQueryAllowedListResponse]
	if err := c.GET("/v5/asset/deposit/query-allowed-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spot-margin-trade/set-pledge-token
func (c *Client) PostSpotMarginTradeSetPledgeToken(req models.PostSpotMarginTradeSetPledgeTokenRequest) (*models.PostSpotMarginTradeSetPledgeTokenResponse, error) {
	var respBody models.Response[models.PostSpotMarginTradeSetPledgeTokenResponse]
	if err := c.POST("/v5/spot-margin-trade/set-pledge-token", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

