// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/ins-loan/ensure-tokens-convert
func (c *Client) GetInsLoanEnsureTokensConvert(req models.GetInsLoanEnsureTokensConvertRequest) (*models.GetInsLoanEnsureTokensConvertResponse, error) {
	var respBody models.Response[models.GetInsLoanEnsureTokensConvertResponse]
	if err := c.GET("/v5/ins-loan/ensure-tokens-convert", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/ins-loan/loan-order
func (c *Client) GetInsLoanLoanOrder(req models.GetInsLoanLoanOrderRequest) (*models.GetInsLoanLoanOrderResponse, error) {
	var respBody models.Response[models.GetInsLoanLoanOrderResponse]
	if err := c.GET("/v5/ins-loan/loan-order", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/ins-loan/ltv-convert
func (c *Client) GetInsLoanLtvConvert(req models.GetInsLoanLtvConvertRequest) (*models.GetInsLoanLtvConvertResponse, error) {
	var respBody models.Response[models.GetInsLoanLtvConvertResponse]
	if err := c.GET("/v5/ins-loan/ltv-convert", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/ins-loan/product-infos
func (c *Client) GetInsLoanProductInfos(req models.GetInsLoanProductInfosRequest) (*models.GetInsLoanProductInfosResponse, error) {
	var respBody models.Response[models.GetInsLoanProductInfosResponse]
	if err := c.GET("/v5/ins-loan/product-infos", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/ins-loan/repaid-history
func (c *Client) GetInsLoanRepaidHistory(req models.GetInsLoanRepaidHistoryRequest) (*models.GetInsLoanRepaidHistoryResponse, error) {
	var respBody models.Response[models.GetInsLoanRepaidHistoryResponse]
	if err := c.GET("/v5/ins-loan/repaid-history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/ins-loan/association-uid
func (c *Client) PostInsLoanAssociationUid(req models.PostInsLoanAssociationUidRequest) (*models.PostInsLoanAssociationUidResponse, error) {
	var respBody models.Response[models.PostInsLoanAssociationUidResponse]
	if err := c.POST("/v5/ins-loan/association-uid", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

