// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/spread/execution/list
func (c *Client) GetSpreadExecutionList(req models.GetSpreadExecutionListRequest) (*models.GetSpreadExecutionListResponse, error) {
	var respBody models.Response[models.GetSpreadExecutionListResponse]
	if err := c.GET("/v5/spread/execution/list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/instrument
func (c *Client) GetSpreadInstrument(req models.GetSpreadInstrumentRequest) (*models.GetSpreadInstrumentResponse, error) {
	var respBody models.Response[models.GetSpreadInstrumentResponse]
	if err := c.GET("/v5/spread/instrument", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/order/history
func (c *Client) GetSpreadOrderHistory(req models.GetSpreadOrderHistoryRequest) (*models.GetSpreadOrderHistoryResponse, error) {
	var respBody models.Response[models.GetSpreadOrderHistoryResponse]
	if err := c.GET("/v5/spread/order/history", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/order/realtime
func (c *Client) GetSpreadOrderRealtime(req models.GetSpreadOrderRealtimeRequest) (*models.GetSpreadOrderRealtimeResponse, error) {
	var respBody models.Response[models.GetSpreadOrderRealtimeResponse]
	if err := c.GET("/v5/spread/order/realtime", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/orderbook
func (c *Client) GetSpreadOrderbook(req models.GetSpreadOrderbookRequest) (*models.GetSpreadOrderbookResponse, error) {
	var respBody models.Response[models.GetSpreadOrderbookResponse]
	if err := c.GET("/v5/spread/orderbook", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/recent-trade
func (c *Client) GetSpreadRecentTrade(req models.GetSpreadRecentTradeRequest) (*models.GetSpreadRecentTradeResponse, error) {
	var respBody models.Response[models.GetSpreadRecentTradeResponse]
	if err := c.GET("/v5/spread/recent-trade", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/spread/tickers
func (c *Client) GetSpreadTickers(req models.GetSpreadTickersRequest) (*models.GetSpreadTickersResponse, error) {
	var respBody models.Response[models.GetSpreadTickersResponse]
	if err := c.GET("/v5/spread/tickers", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spread/order/amend
func (c *Client) PostSpreadOrderAmend(req models.PostSpreadOrderAmendRequest) (*models.PostSpreadOrderAmendResponse, error) {
	var respBody models.Response[models.PostSpreadOrderAmendResponse]
	if err := c.POST("/v5/spread/order/amend", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spread/order/cancel
func (c *Client) PostSpreadOrderCancel(req models.PostSpreadOrderCancelRequest) (*models.PostSpreadOrderCancelResponse, error) {
	var respBody models.Response[models.PostSpreadOrderCancelResponse]
	if err := c.POST("/v5/spread/order/cancel", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spread/order/cancel-all
func (c *Client) PostSpreadOrderCancelAll(req models.PostSpreadOrderCancelAllRequest) (*models.PostSpreadOrderCancelAllResponse, error) {
	var respBody models.Response[models.PostSpreadOrderCancelAllResponse]
	if err := c.POST("/v5/spread/order/cancel-all", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/spread/order/create
func (c *Client) PostSpreadOrderCreate(req models.PostSpreadOrderCreateRequest) (*models.PostSpreadOrderCreateResponse, error) {
	var respBody models.Response[models.PostSpreadOrderCreateResponse]
	if err := c.POST("/v5/spread/order/create", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

