// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/affiliate/aff-user-list
func (c *Client) GetAffiliateAffUserList(req models.GetAffiliateAffUserListRequest) (*models.GetAffiliateAffUserListResponse, error) {
	var respBody models.Response[models.GetAffiliateAffUserListResponse]
	if err := c.GET("/v5/affiliate/aff-user-list", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/user/aff-customer-info
func (c *Client) GetUserAffCustomerInfo(req models.GetUserAffCustomerInfoRequest) (*models.GetUserAffCustomerInfoResponse, error) {
	var respBody models.Response[models.GetUserAffCustomerInfoResponse]
	if err := c.GET("/v5/user/aff-customer-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

