// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// GET /v5/broker/account-info
func (c *Client) GetBrokerAccountInfo(req models.GetBrokerAccountInfoRequest) (*models.GetBrokerAccountInfoResponse, error) {
	var respBody models.Response[models.GetBrokerAccountInfoResponse]
	if err := c.GET("/v5/broker/account-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/broker/asset/query-sub-member-deposit-record
func (c *Client) GetBrokerAssetQuerySubMemberDepositRecord(req models.GetBrokerAssetQuerySubMemberDepositRecordRequest) (*models.GetBrokerAssetQuerySubMemberDepositRecordResponse, error) {
	var respBody models.Response[models.GetBrokerAssetQuerySubMemberDepositRecordResponse]
	if err := c.GET("/v5/broker/asset/query-sub-member-deposit-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// GET /v5/broker/earnings-info
func (c *Client) GetBrokerEarningsInfo(req models.GetBrokerEarningsInfoRequest) (*models.GetBrokerEarningsInfoResponse, error) {
	var respBody models.Response[models.GetBrokerEarningsInfoResponse]
	if err := c.GET("/v5/broker/earnings-info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/broker/award/distribute-award
func (c *Client) PostBrokerAwardDistributeAward(req models.PostBrokerAwardDistributeAwardRequest) (*models.PostBrokerAwardDistributeAwardResponse, error) {
	var respBody models.Response[models.PostBrokerAwardDistributeAwardResponse]
	if err := c.POST("/v5/broker/award/distribute-award", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/broker/award/distribution-record
func (c *Client) PostBrokerAwardDistributionRecord(req models.PostBrokerAwardDistributionRecordRequest) (*models.PostBrokerAwardDistributionRecordResponse, error) {
	var respBody models.Response[models.PostBrokerAwardDistributionRecordResponse]
	if err := c.POST("/v5/broker/award/distribution-record", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

// POST /v5/broker/award/info
func (c *Client) PostBrokerAwardInfo(req models.PostBrokerAwardInfoRequest) (*models.PostBrokerAwardInfoResponse, error) {
	var respBody models.Response[models.PostBrokerAwardInfoResponse]
	if err := c.POST("/v5/broker/award/info", req, &respBody); err != nil { return nil, err }
	return &respBody.Result, nil
}

