// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
	"github.com/DawnKosmos/bybit-go5/models"
)

// V5 Private subscribe wrappers. These delegate to ws.Stream methods and
// accept V5-typed callbacks. Unversioned wrappers in websocket_private.go
// call into these to represent "latest".

func PositionV5(api WsPrivateAPI, fn func(e *models.WsPositionV5)) error {
	return api.Position(fn)
}

func ExecutionV5(api WsPrivateAPI, fn func(e *models.WsExecutionV5)) error {
	return api.Execution(fn)
}

func OrderV5(api WsPrivateAPI, fn func(e *models.WsOrderV5)) error {
	return api.Order(fn)
}

func WalletV5(api WsPrivateAPI, fn func(e *models.WsWalletV5)) error {
	return api.Wallet(fn)
}

func GreekV5(api WsPrivateAPI, fn func(e *models.WsGreekV5)) error {
	return api.Greek(fn)
}
