// Code generated by bybitgen; DO NOT EDIT.
package bybit

import (
    "github.com/DawnKosmos/bybit-go5/models"
)

// Latest (currently V5) Public subscribe wrappers.
// These call their V5 counterparts. When bumping latest, update delegates.

func Orderbook(api WsPublicAPI, symbol string, depth int, fn func(e *models.WsOrderbook)) error {
    return OrderbookV5(api, symbol, depth, fn)
}

func PublicTrade(api WsPublicAPI, symbol string, fn func(e *models.WsTrade)) error {
    return PublicTradeV5(api, symbol, fn)
}

func TickerOption(api WsPublicAPI, symbol string, fn func(e *models.WsTickerOption)) error {
    return TickerOptionV5(api, symbol, fn)
}

func TickerLinear(api WsPublicAPI, symbol string, fn func(e *models.WsTickerLinear)) error {
    return TickerLinearV5(api, symbol, fn)
}

func TickerSpot(api WsPublicAPI, symbol string, fn func(e *models.WsTickerSpot)) error {
    return TickerSpotV5(api, symbol, fn)
}

func Kline(api WsPublicAPI, symbol string, interval string, fn func(e *models.WsKline)) error {
    return KlineV5(api, symbol, interval, fn)
}

func Liquidation(api WsPublicAPI, symbol string, fn func(e *models.WsLiquidation)) error {
    return LiquidationV5(api, symbol, fn)
}

func LeveragedTokenKline(api WsPublicAPI, symbol string, interval string, fn func(e *models.WsLTKline)) error {
    return LeveragedTokenKlineV5(api, symbol, interval, fn)
}

func LeveragedTokenTicker(api WsPublicAPI, symbol string, fn func(e *models.WsLTTicker)) error {
    return LeveragedTokenTickerV5(api, symbol, fn)
}

func LeveragedTokenNav(api WsPublicAPI, symbol string, fn func(e *models.WsLTNav)) error {
    return LeveragedTokenNavV5(api, symbol, fn)
}
