// Code generated by bybitgen; DO NOT EDIT.
package bybit

import "github.com/DawnKosmos/bybit-go5/models"

// Latest (currently V5) Private subscribe wrappers.
// These call their V5 counterparts. When bumping latest, update delegates.

func Position(api WsPrivateAPI, fn func(e *models.WsPosition)) error {
    return PositionV5(api, fn)
}

func Execution(api WsPrivateAPI, fn func(e *models.WsExecution)) error {
    return ExecutionV5(api, fn)
}

func Order(api WsPrivateAPI, fn func(e *models.WsOrder)) error {
    return OrderV5(api, fn)
}

func Wallet(api WsPrivateAPI, fn func(e *models.WsWallet)) error {
    return WalletV5(api, fn)
}

func Greek(api WsPrivateAPI, fn func(e *models.WsGreek)) error {
    return GreekV5(api, fn)
}
