// Code generated by bybitgen; DO NOT EDIT.
package models

// GET /v5/affiliate/aff-user-list
type GetAffiliateAffUserListRequest struct {
	Size int64 `url:"size,omitempty"` // Limit for data size per page. [`0`, `1000`]. Default: `0`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
	NeedDeposit bool `url:"needDeposit,omitempty"` // `true`: return deposit info; `false`(default): does not return deposit info
	Need30 bool `url:"need30,omitempty"` // `true`: return 30 days trading info; `false`(default): does not return 30 days trading info
	Need365 bool `url:"need365,omitempty"` // `true`: return 365 days trading info; `false`(default): does not return 365 days trading info
}

type GetAffiliateAffUserListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/user/aff-customer-info
type GetUserAffCustomerInfoRequest struct {
	Uid string `url:"uid"` // The master account UID of affiliate's client
}

type GetUserAffCustomerInfoResponse struct {
	// TODO: fill in response fields parsed from docs
}

