// Code generated by bybitgen; DO NOT EDIT.
package models

// GET /v5/asset/coin/query-info
type GetAssetCoinQueryInfoRequest struct {
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
}

type GetAssetCoinQueryInfoResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/delivery-record
type GetAssetDeliveryRecordRequest struct {
	Category string `url:"category"` // Product type [UTA2.0](../acct-mode#uta-20): `inverse`(inverse futures), `linear`(USDT/USDC futures), `option` [UTA1.0](../acct-mode#uta-10): `linear`(USDT/USDC futures), `option`
	Symbol string `url:"symbol,omitempty"` // Symbol name, like `BTCUSDT`, uppercase only
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) startTime and endTime are not passed, return 30 days by default Only startTime is passed, return range between startTime and startTime + 30 days Only endTime is passed, return range between endTime - 30 days and endTime If both are passed, the rule is endTime - startTime <= 30 days
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms)
	ExpDate string `url:"expDate,omitempty"` // Expiry date. `25MAR22`. Default: return all
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `20`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetDeliveryRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/deposit/query-address
type GetAssetDepositQueryAddressRequest struct {
	Coin string `url:"coin"` // Coin, uppercase only
	ChainType string `url:"chainType,omitempty"` // Please use the value of `>> chain` from [coin-info](../coin-info#) endpoint
}

type GetAssetDepositQueryAddressResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/deposit/query-internal-record
type GetAssetDepositQueryInternalRecordRequest struct {
	TxID string `url:"txID,omitempty"` // Internal transfer transaction ID
	StartTime int64 `url:"startTime,omitempty"` // Start time (ms). Default value: 30 days before the current time
	EndTime int64 `url:"endTime,omitempty"` // End time (ms). Default value: current time
	Coin string `url:"coin,omitempty"` // Coin name: for example, BTC. Default value: all
	Cursor string `url:"cursor,omitempty"` // Cursor, used for pagination
	Limit int64 `url:"limit,omitempty"` // Number of items per page, [`1`, `50`]. Default value: 50
}

type GetAssetDepositQueryInternalRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/deposit/query-record
type GetAssetDepositQueryRecordRequest struct {
	Id string `url:"id,omitempty"` // Internal ID: Can be used to uniquely identify and filter the deposit. When combined with other parameters, this field takes the highest priority
	TxID string `url:"txID,omitempty"` // Transaction ID: Please note that data generated before Jan 1, 2024 cannot be queried using txID
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `50`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetDepositQueryRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/deposit/query-sub-member-address
type GetAssetDepositQuerySubMemberAddressRequest struct {
	Coin string `url:"coin"` // Coin, uppercase only
	ChainType string `url:"chainType"` // Please use the value of `chain` from [coin-info](../coin-info#) endpoint
	SubMemberId string `url:"subMemberId"` // Sub user ID
}

type GetAssetDepositQuerySubMemberAddressResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/deposit/query-sub-member-record
type GetAssetDepositQuerySubMemberRecordRequest struct {
	Id string `url:"id,omitempty"` // Internal ID: Can be used to uniquely identify and filter the deposit. When combined with other parameters, this field takes the highest priority
	TxID string `url:"txID,omitempty"` // Transaction ID: Please note that data generated before Jan 1, 2024 cannot be queried using txID
	SubMemberId string `url:"subMemberId"` // Sub UID
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `50`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetDepositQuerySubMemberRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/exchange/convert-result-query
type GetAssetExchangeConvertResultQueryRequest struct {
	QuoteTxId string `url:"quoteTxId"` // Quote tx ID
	AccountType string `url:"accountType"` // Wallet type
}

type GetAssetExchangeConvertResultQueryResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/exchange/order-record
type GetAssetExchangeOrderRecordRequest struct {
	FromCoin string `url:"fromCoin,omitempty"` // The currency to convert from, uppercase only. e.g,`BTC`
	ToCoin string `url:"toCoin,omitempty"` // The currency to convert to, uppercase only. e.g,`USDT`
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `10`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetExchangeOrderRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/exchange/query-coin-list
type GetAssetExchangeQueryCoinListRequest struct {
	AccountType string `url:"accountType"` // Wallet type `eb_convert_funding` `eb_convert_uta` `eb_convert_spot` `eb_convert_contract` `eb_convert_inverse`
	Coin string `url:"coin,omitempty"` // Coin, uppercase only Convert from coin (coin to sell) when side=0, coin field is ignored
	Side int64 `url:"side,omitempty"` // `0`: fromCoin list, the balance is given if you have it; `1`: toCoin list (coin to buy) when side=1 and coin field is filled, it returns toCoin list based on coin field
}

type GetAssetExchangeQueryCoinListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/exchange/query-convert-history
type GetAssetExchangeQueryConvertHistoryRequest struct {
	AccountType string `url:"accountType,omitempty"` // Wallet type Supports passing multiple types, separated by comma e.g., <code>eb_convert_funding,eb_convert_uta</code> Return all wallet types data if not passed
	Index int64 `url:"index,omitempty"` // Page number started from 1 1st page by default
	Limit int64 `url:"limit,omitempty"` // Page size 20 records by default up to 100 records, return 100 when exceeds 100
}

type GetAssetExchangeQueryConvertHistoryResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/settlement-record
type GetAssetSettlementRecordRequest struct {
	Category string `url:"category"` // Product type [UTA2.0](../acct-mode#uta-20): `linear`(USDC contract) [UTA1.0](../acct-mode#uta-10): `linear`(USDC contract)
	Symbol string `url:"symbol,omitempty"` // Symbol name, like `BTCPERP`, uppercase only
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) startTime and endTime are not passed, return 30 days by default Only startTime is passed, return range between startTime and startTime + 30 days Only endTime is passed, return range between endTime-30 days and endTime If both are passed, the rule is endTime - startTime <= 30 days
	EndTime int64 `url:"endTime,omitempty"` // The end time. timestamp (ms)
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `20`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetSettlementRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-account-coin-balance
type GetAssetTransferQueryAccountCoinBalanceRequest struct {
	MemberId string `url:"memberId,omitempty"` // UID. **Required** when querying sub UID balance with master api key
	ToMemberId string `url:"toMemberId,omitempty"` // UID. **Required** when querying the transferable balance between different UIDs
	AccountType string `url:"accountType"` // Account type
	ToAccountType string `url:"toAccountType,omitempty"` // To account type. **Required** when querying the transferable balance between different account types
	Coin string `url:"coin"` // Coin, uppercase only
	WithBonus int64 `url:"withBonus,omitempty"` // `0`(default): not query bonus. `1`: query bonus
	WithTransferSafeAmount int64 `url:"withTransferSafeAmount,omitempty"` // Whether query delay withdraw/transfer safe amount `0`(default): false, `1`: true What is [delay withdraw amount](delay-amount#)?
	WithLtvTransferSafeAmount int64 `url:"withLtvTransferSafeAmount,omitempty"` // For OTC loan users in particular, you can check the transferable amount under risk level `0`(default): false, `1`: true `toAccountType` is mandatory
}

type GetAssetTransferQueryAccountCoinBalanceResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-account-coins-balance
type GetAssetTransferQueryAccountCoinsBalanceRequest struct {
	MemberId string `url:"memberId,omitempty"` // User Id. It is <b>required</b> when you use master api key to check sub account coin balance
	AccountType string `url:"accountType"` // Account type
	Coin string `url:"coin,omitempty"` // Coin name, uppercase only Query all coins if not passed Can query multiple coins, separated by comma. `USDT,USDC,ETH` **Note:** this field is **mandatory** for accountType=`UNIFIED`, and supports up to 10 coins each request
	WithBonus int64 `url:"withBonus,omitempty"` // `0`(default): not query bonus. `1`: query bonus
}

type GetAssetTransferQueryAccountCoinsBalanceResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-asset-info
type GetAssetTransferQueryAssetInfoRequest struct {
	AccountType string `url:"accountType"` // Account type. `SPOT`
	Coin string `url:"coin,omitempty"` // Coin name, uppercase only
}

type GetAssetTransferQueryAssetInfoResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-inter-transfer-list
type GetAssetTransferQueryInterTransferListRequest struct {
	TransferId string `url:"transferId,omitempty"` // UUID. Use the one you generated in [createTransfer](create-inter-transfer#response-parameters)
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
	Status string `url:"status,omitempty"` // Transfer status
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `20`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetTransferQueryInterTransferListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-sub-member-list
type GetAssetTransferQuerySubMemberListRequest struct {
}

type GetAssetTransferQuerySubMemberListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-transfer-coin-list
type GetAssetTransferQueryTransferCoinListRequest struct {
	FromAccountType string `url:"fromAccountType"` // From account type
	ToAccountType string `url:"toAccountType"` // To account type
}

type GetAssetTransferQueryTransferCoinListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/transfer/query-universal-transfer-list
type GetAssetTransferQueryUniversalTransferListRequest struct {
	TransferId string `url:"transferId,omitempty"` // UUID. Use the one you generated in [createTransfer](create-inter-transfer#response-parameters)
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
	Status string `url:"status,omitempty"` // Transfer status. `SUCCESS`,`FAILED`,`PENDING`
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms) _Note: the query logic is actually effective based on **second** level_
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `20`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetTransferQueryUniversalTransferListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/withdraw/query-record
type GetAssetWithdrawQueryRecordRequest struct {
	WithdrawID string `url:"withdrawID,omitempty"` // Withdraw ID
	TxID string `url:"txID,omitempty"` // Transaction hash ID
	Coin string `url:"coin,omitempty"` // Coin, uppercase only
	WithdrawType int64 `url:"withdrawType,omitempty"` // Withdraw type. `0`(default): on chain. `1`: off chain. `2`: all
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms)
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms)
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `50`]. Default: `50`
	Cursor string `url:"cursor,omitempty"` // Cursor. Use the `nextPageCursor` token from the response to retrieve the next page of the result set
}

type GetAssetWithdrawQueryRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/withdraw/vasp/list
type GetAssetWithdrawVaspListRequest struct {
}

type GetAssetWithdrawVaspListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/asset/withdraw/withdrawable-amount
type GetAssetWithdrawWithdrawableAmountRequest struct {
	Coin string `url:"coin"` // Coin name, uppercase only
}

type GetAssetWithdrawWithdrawableAmountResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/deposit/deposit-to-account
type PostAssetDepositDepositToAccountRequest struct {
	AccountType string `json:"accountType"` // Account type <code>UNIFIED</code> <code>SPOT</code> <code>CONTRACT</code> <code>FUND</code>
}

type PostAssetDepositDepositToAccountResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/exchange/convert-execute
type PostAssetExchangeConvertExecuteRequest struct {
	QuoteTxId string `json:"quoteTxId"` // The quote tx ID from [Request a Quote](apply-quote#response-parameters)
}

type PostAssetExchangeConvertExecuteResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/exchange/quote-apply
type PostAssetExchangeQuoteApplyRequest struct {
	AccountType string `json:"accountType"` // Wallet type
	FromCoin string `json:"fromCoin"` // Convert from coin (coin to sell)
	ToCoin string `json:"toCoin"` // Convert to coin (coin to buy)
	RequestCoin string `json:"requestCoin"` // Request coin, same as fromCoin In the future, we may support requestCoin=toCoin
	RequestAmount string `json:"requestAmount"` // request coin amount (the amount you want to sell)
	FromCoinType string `json:"fromCoinType,omitempty"` // `crypto`
	ToCoinType string `json:"toCoinType,omitempty"` // `crypto`
	ParamType string `json:"paramType,omitempty"` // `opFrom`, mainly used for API broker user
	ParamValue string `json:"paramValue,omitempty"` // Broker ID, mainly used for API broker user
	RequestId string `json:"requestId,omitempty"` // Customised request ID a maximum length of 36 Generally it is useless, but it is convenient to track the quote request internally if you fill this field
}

type PostAssetExchangeQuoteApplyResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/transfer/inter-transfer
type PostAssetTransferInterTransferRequest struct {
	TransferId string `json:"transferId"` // [UUID](https://www.uuidgenerator.net/dev-corner). Please manually generate a UUID
	Coin string `json:"coin"` // Coin, uppercase only
	Amount string `json:"amount"` // Amount
	FromAccountType string `json:"fromAccountType"` // From account type
	ToAccountType string `json:"toAccountType"` // To account type
}

type PostAssetTransferInterTransferResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/transfer/universal-transfer
type PostAssetTransferUniversalTransferRequest struct {
	TransferId string `json:"transferId"` // [UUID](https://www.uuidgenerator.net/dev-corner). Please manually generate a UUID
	Coin string `json:"coin"` // Coin, uppercase only
	Amount string `json:"amount"` // Amount
	FromMemberId int64 `json:"fromMemberId"` // From UID
	ToMemberId int64 `json:"toMemberId"` // To UID
	FromAccountType string `json:"fromAccountType"` // From account type
	ToAccountType string `json:"toAccountType"` // To account type
}

type PostAssetTransferUniversalTransferResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/withdraw/cancel
type PostAssetWithdrawCancelRequest struct {
	Id string `json:"id"` // Withdrawal ID
}

type PostAssetWithdrawCancelResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/asset/withdraw/create
type PostAssetWithdrawCreateRequest struct {
	Coin string `json:"coin"` // Coin, uppercase only
	Chain string `json:"chain,omitempty"` // Chain `forceChain`=0 or 1: this field is **required** `forceChain`=2: this field can be null
	Address string `json:"address"` // `forceChain`=0 or 1: fill wallet address, and make sure you add address in the [address book](https://www.bybit.com/user/assets/money-address) first. Please note that the address is case sensitive, so use the exact same address added in address book `forceChain`=2: fill Bybit UID, and it can only be another Bybit **main** account UID. Make sure you add UID in the [address book](https://www.bybit.com/user/assets/money-address) first
	Tag string `json:"tag,omitempty"` // Tag **Required** if tag exists in the wallet address list. **Note**: please do not set a tag/memo in the address book if the chain does not support tag
	Amount string `json:"amount"` // Withdraw amount
	Timestamp int64 `json:"timestamp"` // Current timestamp (ms). Used for preventing from withdraw replay
	ForceChain int64 `json:"forceChain,omitempty"` // Whether or not to force an on-chain withdrawal `0`(default): If the address is parsed out to be an internal address, then internal transfer (**Bybit main account only**) `1`: Force the withdrawal to occur on-chain `2`: Use UID to withdraw
	AccountType string `json:"accountType"` // Select the wallet to be withdrawn from `FUND`: Funding wallet `UTA`: System transfers the funds to Funding wallet to withdraw `FUND,UTA`: For combo withdrawals, funds will be deducted from the Funding wallet first. If the balance is insufficient, the remaining amount will be deducted from the UTA wallet. `SPOT`: withdraw from spot wallet (classic account only)
	FeeType int64 `json:"feeType,omitempty"` // Handling fee option `0`(default): input amount is the actual amount received, so you have to calculate handling fee manually `1`: input amount is not the actual amount you received, the system will help to deduct the handling fee automatically
	RequestId string `json:"requestId,omitempty"` // Customised ID, globally unique, it is used for idempotent verification A combination of letters (case sensitive) and numbers, which can be pure letters or pure numbers and the length must be between 1 and 32 digits
	Beneficiary string `json:"beneficiary,omitempty"` // Travel rule info. It is **required** for kyc/kyb=KOR (Korean), kyc=IND (India) users, and users who registered in [Bybit Turkey(TR)](https://www.bybit-tr.com/en-TR/), [Bybit Kazakhstan(KZ)](https://www.bybit.kz/kk-KAZ/), Bybit Indonesia (ID)
}

type PostAssetWithdrawCreateResponse struct {
	// TODO: fill in response fields parsed from docs
}

