// Code generated by bybitgen; DO NOT EDIT.
package models

// GET /v5/asset/deposit/query-allowed-list
type GetAssetDepositQueryAllowedListRequest struct {
}

type GetAssetDepositQueryAllowedListResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/spot-margin-trade/set-pledge-token
type PostSpotMarginTradeSetPledgeTokenRequest struct {
}

type PostSpotMarginTradeSetPledgeTokenResponse struct {
	// TODO: fill in response fields parsed from docs
}

