// Code generated by bybitgen; DO NOT EDIT.
package models

// GET /v5/spot-lever-token/info
type GetSpotLeverTokenInfoRequest struct {
	LtCoin string `url:"ltCoin,omitempty"` // Abbreviation of the LT, such as `BTC3L`
}

type GetSpotLeverTokenInfoResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/spot-lever-token/order-record
type GetSpotLeverTokenOrderRecordRequest struct {
	LtCoin string `url:"ltCoin,omitempty"` // Abbreviation of the LT, such as BTC3L
	OrderId string `url:"orderId,omitempty"` // Order ID
	StartTime int64 `url:"startTime,omitempty"` // The start timestamp (ms)
	EndTime int64 `url:"endTime,omitempty"` // The end timestamp (ms)
	Limit int64 `url:"limit,omitempty"` // Limit for data size per page. [`1`, `500`]. Default: `100`
	LtOrderType int64 `url:"ltOrderType,omitempty"` // LT order type. `1`: purchase, `2`: redemption
	SerialNo string `url:"serialNo,omitempty"` // Serial number
}

type GetSpotLeverTokenOrderRecordResponse struct {
	// TODO: fill in response fields parsed from docs
}

// GET /v5/spot-lever-token/reference
type GetSpotLeverTokenReferenceRequest struct {
	LtCoin string `url:"ltCoin"` // Abbreviation of the LT, such as BTC3L
}

type GetSpotLeverTokenReferenceResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/spot-lever-token/purchase
type PostSpotLeverTokenPurchaseRequest struct {
	LtCoin string `json:"ltCoin"` // Abbreviation of the LT, such as BTC3L
	LtAmount string `json:"ltAmount"` // Purchase amount
	SerialNo string `json:"serialNo,omitempty"` // Serial number
}

type PostSpotLeverTokenPurchaseResponse struct {
	// TODO: fill in response fields parsed from docs
}

// POST /v5/spot-lever-token/redeem
type PostSpotLeverTokenRedeemRequest struct {
	LtCoin string `json:"ltCoin"` // Abbreviation of the LT, such as BTC3L
	Quantity string `json:"quantity,omitempty"` // Redeem quantity of LT
	SerialNo string `json:"serialNo,omitempty"` // Serial number
}

type PostSpotLeverTokenRedeemResponse struct {
	// TODO: fill in response fields parsed from docs
}

